### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jrburke** [iammerrick/Squire.js#1]
I am still new to the needs for mock testing. So this may be ill-informed. If it is, then listing where this falls short in the readme may help distinguish the use cases:

For mock testing, it should be enough just to call define() with a named module that has the mock, then require as usual. So, if there is a module 'bar' that depends on 'foo', and 'foo' will be mocked:

``` javascript
var mock1Require = requirejs.config({
    //create a context for the mock
    context: 'mock1',
    paths: {
        //Either store the mock as a separate file,
        //or do the inline define below
        foo: 'mocks/foo1'
    }
});

//If not using the paths to direct 'foo' to a separate mock
//file, inline define it:
define('foo', function () {
    return {};
});

mock1Require(['bar'], function(bar) {
    //Do tests with bar, which will be using the mocked foo
});
```

Looking at the squire API it seems to do more than this, but my first approximation is that it is enough to at least start mock testing. Says the person that does not really do mocks :)

I definitely support raising awareness of how to do mock testing with requirejs. It does seem to come up now and then. I would like to have a resource I could point to for it, maybe link to it on the [testing wiki page](https://github.com/jrburke/requirejs/wiki/Test-frameworks)

**Comment by iammerrick** [comment]
@jrburke Ultimately, thats what Squire.js does. It leverages the multi-context loading and define calls. However it also lets you specify a magic module name called 'mocks' which provides pointers to the dependencies, this way you can leverage Sinon to stub your dependencies accordingly. The trouble with just leveraging "define() -> context" is that you end up with an _enormous_ amount of boilerplate. I am still disappointed with how much boilerplate exists for Squire. I'm wondering if leveraging a build to strip require / define for tests would be worthwhile (and improve test speed). I don't know looking for the best way to solve this problem, it's very important it's solved.

**Comment by iammerrick** [comment]
@jrburke Also, thank you very very much for your time.

**Comment by jrburke** [comment]
I guess the missing piece is the Sinon stuff, does it need something special? Otherwise, for me, it seems like there is just about as much boilerplate as non-modular code. For example, I would expect a browser globals thing to need to load a mock, then load the main library and test file, something like:

``` html
<script src="mocks/foo1.js"></script>
<script src="mainlib.js"></script>
<script src="test.js"></script>
```

where the requirejs one could be like the one above, except that test.js just has the requirejs.config() call in it. I suppose to match the style above:

``` html
<script>
var require = {
    paths: { foo: 'mocks/foo1' },
    deps: ['test']
});
<script>
<script src="require.js"></script>
```

This assumes there is one test run per HTML page. 

If doing it purely in JS, it can just be one call with a declarative config:

``` javascript
requirejs.config({
  context: 'mock1',
  paths: {
      foo: 'mocks/foo1'
  },
  deps: ['testFoo1']
});


requirejs.config({
  context: 'mock2',
  paths: {
      baz: 'mocks/baz1'
  },
  deps: ['testBaz1']
});
```

Maybe the issue is tying all the tests to a unified output? Not sure, but trying to get a better handle on the parts that need extra work. This stuff is still new to me.

**Comment by iammerrick** [comment]
The problem is you need to be able to do multiple mocks per module in a given test file. Re-wiring require.js config or using multiple loaders directly introduces a lot of boilerplate in these cases.

The Sinon/Mocks component can be explained like this.

``` javascript

var injector = new Squire();
injector
  .store('CrazyCalculatorDependency')
  .require(['utilities/Calculator', 'mocks'], function(Calculator, mocks) {
    var add = mocks.CrazyCalculatorDependency.add = sinon.spy();
    var complete = mocks.CrazyCalculatorDependency.complete = sinon.spy();
    Calculator.add(1, 4);
    expect(add).to.be.called.before(complete);
  });
```

In the case above `CrazyCalculatorDependency` is a dependency of `utilities/Calculator` normally these dependencies are private to the particular module consuming them. However, we want to test Calculator and Calculator alone so we stub out it's dependencies, we can't leverage a lot of the great stubbing functionality of sinon without having a handle to our dependencies. Does that make sense?

Also in terms of the boilerplate problem... All the injector/store code loading is relatively verbose and I suppose you are right that others just have that in script tags for their pages, none the less. I feel a test should not be concerned about loading code but about executing it properly. Any ideas on how to mitigate this pain (huge percentage of your test for loading code and mocks) would be greatly appreciated.

**Comment by iammerrick** [comment]
@jrburke It's worth noting explicitly... `mocks.CrazyCalculatorDependency` is a handle to the downloaded and referenced dependency of `utilities/Calculator`. Sinon mutates existing variables.
