### ISSUE TITLE
Starting tests as part of config results in multiple executions

### ISSUE THREAD

**Issue by mokkabonna** [iammerrick/Squire.js#45]
```
requirejs.config({
  baseUrl: '/base/app',
  //etc

  // ask Require.js to load these files (all our tests)
  deps: ['test1', 'test2'],

  // start test run, once Require.js is done
  callback: window.__karma__.start
});
```

According to the karma guide for requirejs this is how you should do it.

It seems Squire when creating a new instance is using this config and refires the callback function, meaning it runs the tests multiple times.

Resolved it with using no `deps` and `callback` in the config, but rather calling `require(tests, window.__karma__.start);` after the config call.

I do not know if it is because of a bug in Squire, or if this is expected behaviour. But it would have been nice if this was warned about in the squire README.

Something like, "any original callbacks on the config will be fired again when you do `new Squire().require([...], callback)`

**Comment by iammerrick** [comment]
It certainly is expected behavior and I agree we ought to document a blessed karma path. (I am thinking maybe even a karma plugin). I'm sorry for time that you were frustrated trying to figure this out.

**Comment by ghost** [comment]
Thanks for leaving this comment!  Been struggling with this issue and was about ready to scream.

**Comment by alexaivars** [comment]
Would love to se this documented, spent a good handfull of hair figuring this out.

**Comment by VarunBalakrishna** [comment]
I ran into the problem as well, and I fixed it the same way.

However, I also noticed that Squire ignores the `deps` key in the configuration that it passes to the the load method. I can only assume this was to avoid reloading deps every time a new context is created. Would it make sense to also ignore the `callback` key in the config? Since the `callback` key exists to be used in conjunction with `deps`, and we are ignoring deps anyway...

This would fix the above mentioned issue without any need to have any custom Karma test-main code.
