### ISSUE TITLE
Cannot mock an array

### ISSUE THREAD

**Issue by JakeChampion** [iammerrick/Squire.js#48]
If the required module you are trying to mock is a simple array:

``` JS
"use strict";
define('emptyArray', function() {
    return [];
});
```

``` JS
"use strict";
define('thingToTest', ['emptyArray'], function(emptyArray) {
    if (emptyArray.length > 0) {
        return false;
    } else {
        return true;
    }
});
```

And you need to mock it to contain specific items for a test:

``` JS
"use strict";
define(["squire"], function(Squire) {
    describe("thingToTest", function() {
        it("Will fail as squire can't mock an array", function() {
            var thingToTest;
            var emptyArrayMock;
            var ready;

            emptyArrayMock = [{},{},{}];

            new Squire()
                .mock('emptyArray', emptyArrayMock)
                .require(['thingToTest'], function(thing) {
                    thingToTest = thing;
                    ready = true;
                });

            waitsFor(function() {
                return ready;
            });

            runs(function() {
                expect(thingToTest).toEqual(false);
            });
        });
    });
});
```

SquireJS will assign nothing to the dependency, leaving it undefined.

**Comment by alexandreFromage** [comment]
Hi Jake,

This is due to _RequireJs_ itself. It is trying to smart-guess what you are passing it when calling define:

```
define = function (name, deps, callback){...}
```

Basically, if the second param (_deps_) is an array, it will handle it as a dependency. Otherwise, it will handle it as a callback and will set _deps_ to be _callback_:

```
if (!isArray(deps)) {
    callback = deps;
    deps = null;
}
```

What happens in _isArray_ is that _toString_ is called on the object and the result is compared against _'[object Array]'_.

A quick hack can be to create an object with an array prototype. Hence it will behave as an array but won't be treated as such by _Require_.
Eg:

```
function ArrayHack() { };

ArrayHack.prototype = [];

var mock = new ArrayHack();
mock.push('1');
mock.push('2');
 ...
new Squire().mock("module",mock);
```

**Comment by alexandreFromage** [comment]
Submitted a pull request to close that issue.
